theme: minima

title: Septolum (Nat Marriage)

description: My homepage for occasional posts

base_url: "https://septolum.github.io"

author: Septolum (Nat Marriage)

email: septolum@gmail.com

twitter_username: Septolum

mastodon:
 - username: Septolum
   instance: masto.ai

github_username: Septolum

header_pages:
  - recipes.md

include:
  - _pages
